#ifndef PLATINUM_INTERNAL_GRAPHICS_H
#define PLATINUM_INTERNAL_GRAPHICS_H

#ifdef PLATINUM_GRAPHICS_VULKAN
#include "_graphics_vulkan.h"
#endif // PLATINUM_GRAPHICS

#endif // PLATINUM_INTERNAL_GRAPHICS_H
